name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  # todo: DRY with build-and-publish.yml
  build:
    # `ubuntu-latest` currently implies 20.04, which doesn't have Python 3.10
    # yet, which is need for revent versions of qsv to work.
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install qsv
      run: ./ci/install-qsv.sh

    - run: ./build.sh
