name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  # todo: DRY with build-and-publish.yml
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install qsv
      run: ./ci/install-qsv.sh

    - run: ./build.sh
